kumuluzee:
  name: ms-user-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  datasources:
    - jndi-name: jdbc/UserDataDS
      connection-url: jdbc:postgresql://localhost:5432/msuser
      username: vwzlirwy
      password: Y-i_Gt9JiZ0-qr0fhQu-Pj0oi1EToBk3
      pool:
        max-size: 3
  dev:
    scan-libraries:
      - ms-user-models
      - ms-user-services
      - ms-user-lib
  openapi-mp:
    ui:
      specification-server: http://52.188.141.107/ms-user
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/UserDataDS
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                            <Configuration name="rides">
                                <Appenders>
                                    <Console name="console" target="SYSTEM_OUT">
                                        <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                    </Console>
                                    <Socket name="logstash" host="af96aeac-0250-4f55-bb51-627ab4111040-ls.logit.io"
                                    port="28826" protocol="udp">
                                        <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                    </Socket>
                                </Appenders>
                                <Loggers>
                                    <!-- Default logger -->
                                    <Root level="all">
                                        <AppenderRef ref="console" level="info" />
                                        <AppenderRef ref="logstash" level="trace" />
                                    </Root>
                                </Loggers>
                            </Configuration>'
rest-properties:
  broken: false